@startuml
|Приложение|
start
fork
if (пользователь зарегистрирован) then (да)
  |Пользователь|
  if (хочет поменять данные) then (да)
    :редактировать профиль;
  else (нет)
    :;
    kill
  endif
else (нет)
  :регистрация;
endif
end fork
|Пользователь|
fork
:выбор места отправления;
:выбор места прибытия;
:выбор тарифа;
end fork
if (выбор способа оплаты) then (картой)
  :ввести данные карты;
  |Приложение|
  fork
  :проверяет корректность данных;
  |Сервер|
  :обрабатывает платеж;
  end fork
|Пользователь|
else (наличными)
  :;
endif
:подтвердить поездку;
fork
|Приложение|
repeat
  :запрос на поиск доступного такси;
  |Сервер|
repeat while (не нашел информацию о ближайшем такси)
|Приложение|
:получает информацию о водителе;
|Водитель|
:подтверждает заказ;
end fork
|Пользователь|
:видит статус заказа;
:видит информацию о водителе;
if (читает отзывы) then (да)
    fork
    :читает отзывы;
    if (записываем номер телефона) then (да)
      |Пользователь|
      :звонит/пишет водителю;
      |Водитель|
      :отвечает;
      |Пользователь|
    else (нет)
      |Пользователь|
      :;
      kill
    endif
    end fork
  else (нет)
    |Пользователь|
    :;
  endif
|Водитель|
:доставил пользователя;
stop
@enduml
